import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const source=readFileSync(new URL("../docs/app.js",import.meta.url),"utf8");
test("canonical economy contains only kiss and love",()=>{assert.match(source,/rewards:\{kiss:0,love:0\}/);assert.doesNotMatch(source,/rewards:\{[^}]*cheek|addReward\(['"](?:cheek|slap|pass)/)});
test("reward additions are isolated",()=>{const rewards={kiss:4,love:90},before={...rewards};rewards.kiss++;assert.equal(rewards.love,before.love);rewards.love+=20;assert.equal(rewards.kiss,before.kiss+1)});
test("160 data-driven achievements are validated",()=>{assert.match(source,/ACHIEVEMENTS\.length===160/);assert.match(source,/new Set\(ACHIEVEMENTS\.map\(a=>a\.id\)\)\.size===160/);assert.match(source,/typeof a\.condition==='function'/)});
test("locked achievement requirements remain secret",()=>{assert.match(source,/date\?a\.rarity\.toUpperCase\(\):'\?\?\?'/);assert.doesNotMatch(source,/83 \/ 100/)});
test("XP supports multiple level-ups and preserves overflow",()=>{const need=l=>Math.round(60+l**1.42*20);let level=1,xp=1000;while(xp>=need(level)){xp-=need(level);level++}assert.ok(level>4);assert.ok(xp>=0&&xp<need(level))});
test("random games bind one internal outcome to their reveal",()=>{assert.match(source,/const outcome=Math\.random\(\)<\.5\?'YAZI':'TURA'/);assert.match(source,/const index=Math\.floor\(Math\.random\(\)\*8\)/);assert.match(source,/wheelRewards\[index\]/)});
test("skill games use precise clocks and cleanup",()=>{assert.match(source,/performance\.now\(\)/);assert.match(source,/cancelAnimationFrame\(raf\)/);assert.match(source,/clearTimeout\(timer\)/)});
